### ISSUE TITLE
won't match the example

### ISSUE THREAD

**Issue by jenn-sweet** [jenn-sweet/dealing-with-whitespace#1]
it says all the tags are rite in mark bot, but it is like 30% off.
It is like my font is too big, but it is the correct.

<img width="948" alt="Screen Shot 2021-03-22 at 3 18 08 PM" src="https://user-images.githubusercontent.com/77341921/112045994-dba2e700-8b21-11eb-865c-83d6e2b76b7f.png">

@raven-rhea

**Comment by raven-rhea** [comment]
I would take the font size off your body and just let be 1 . . . font-size: 1.125rem is the size for the blockquote

**Comment by raven-rhea** [comment]
also there is too much margin on your h1, and it shouldn't be bold, hopefully thats enough to please markbot :)

**Comment by jenn-sweet** [comment]
That was awesome! It was not quite enough to make it happy, I ended up doing some really questionable things...
<img width="264" alt="Screen Shot 2021-03-23 at 10 55 17 AM" src="https://user-images.githubusercontent.com/77341921/112167204-a69ca000-8bc6-11eb-8e19-87ca738c9337.png">
but in the end we won!
Thanks :)

**Comment by raven-rhea** [comment]
Hahaha that's all that matters
